---
galaxy_info:
  role_name: "certs"
  # namespace: yukics
  author: yukics
  description: An Ansible role to setup and manage certificates
  license: GPL-3.0-only
  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags: []

dependencies: []
